services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: portfoliobd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    image: node:latest
    container_name: nextjs_container
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db

  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
