-- CreateEnum
CREATE TYPE "ProjectType" AS ENUM ('WEB_APP', 'MOBILE_APP', 'DESKTOP_APP', 'DATA_SCIENCE', 'MACHINE_LEARNING', 'DIGITAL_IMAGING', 'GAME', 'API', 'LIBRARY', 'CLI', 'OTHER');

-- AlterTable
ALTER TABLE "Thread" ADD COLUMN     "type" "ProjectType" NOT NULL DEFAULT 'OTHER';
